### ISSUE TITLE
qemu-kvm should be replaced by a better "grub install" strategy

### ISSUE THREAD

**Issue by ManuelAmadorAditazz** [Rudd-O/zfs-fedora-installer#1]
alternatively use qemu-kvm stdio to console instead, so we can script the root device password

**Comment by Rudd-O** [comment]
Alright, the initial RAM disk that we create does no longer include a zpool.cache file with labels or anything — it is generated as no-hostonly — so the pool should import fine on first boot in bare metal, by relying on scan import rather than cache import.

My testing rig tests both hostonly and no-hostonly initial RAM disks.  They work okay.
